<!doctype html>
<html lang="bn">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ $campaign_data->name }} | {{ optional($generalsetting)->name }}</title>
    <meta name="description" content="{{ Str::limit(strip_tags($campaign_data->short_description), 155) }}">
    <meta property="og:title" content="{{ $campaign_data->name }}">
    <meta property="og:description" content="{{ Str::limit(strip_tags($campaign_data->short_description), 155) }}">
    @if($campaign_data->banner)<meta property="og:image" content="{{ asset($campaign_data->banner) }}">@endif
    <link rel="shortcut icon" href="{{ asset(optional($generalsetting)->favicon) }}">
    <link href="{{ asset('public/frontEnd/campaign/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('public/frontEnd/campaign/css/all.css') }}" rel="stylesheet">
    <style>
        :root { --brand:#087f5b; --ink:#15231f; --muted:#62716b; --line:#e5ece8; --surface:#f6f9f7; --accent:#e97520; }
        * { box-sizing:border-box } html { scroll-behavior:smooth } body { margin:0; color:var(--ink); background:var(--surface); font-family:system-ui,-apple-system,"Noto Sans Bengali",sans-serif; }
        .lp-shell { max-width:1160px; margin:auto; padding:0 20px 96px; }
        .lp-nav { background:#fff; border-bottom:1px solid var(--line); position:sticky; top:0; z-index:30; }
        .lp-nav-inner { max-width:1160px; min-height:64px; margin:auto; display:flex; align-items:center; justify-content:space-between; padding:10px 20px; gap:15px; }
        .lp-logo { max-height:42px; max-width:160px; object-fit:contain; } .lp-nav a { color:var(--ink); text-decoration:none; font-weight:700; }
        .hero { padding:38px 0 20px; display:grid; grid-template-columns:1.05fr .95fr; gap:34px; align-items:center; }
        .eyebrow { display:inline-flex; align-items:center; gap:7px; padding:7px 11px; color:#086b4d; background:#e7f7ef; border-radius:99px; font-weight:800; font-size:.86rem; }
        h1 { font-size:clamp(2rem,4vw,3.65rem); line-height:1.1; letter-spacing:-.045em; margin:16px 0; font-weight:850; } .hero-copy p { color:var(--muted); font-size:1.1rem; line-height:1.65; } .offer-countdown{display:inline-flex;gap:8px;margin:0 0 15px;flex-wrap:wrap}.offer-countdown span{background:#163a2c;color:#fff;border-radius:7px;padding:6px 9px;font-size:.8rem;font-weight:800}.offer-countdown small{display:block;font-size:.62rem;opacity:.7;text-align:center}
        .hero-media { border-radius:24px; overflow:hidden; background:#dce9e2; box-shadow:0 18px 42px rgba(22,49,38,.13); } .hero-media img { display:block; width:100%; aspect-ratio:1.25; object-fit:cover; }
        .cta { border:0; border-radius:10px; background:var(--brand); color:#fff; font-weight:800; padding:13px 20px; text-decoration:none; display:inline-flex; gap:8px; align-items:center; cursor:pointer; } .cta:hover { color:#fff; background:#066c4c; } .cta-outline { background:#fff;color:var(--brand);border:1px solid #bad9cb; }
        .trust-row { display:grid; grid-template-columns:repeat(3,1fr); gap:12px; margin:20px 0 42px; } .trust { background:#fff; border:1px solid var(--line); border-radius:13px; padding:15px; display:flex; gap:10px; align-items:flex-start; } .trust i { color:var(--brand); font-size:1.25rem; } .trust strong,.trust small { display:block } .trust small { color:var(--muted); margin-top:2px; }
        .section { padding:28px 0; } .section-heading { max-width:690px; margin:0 auto 24px; text-align:center; } h2 { font-size:clamp(1.55rem,3vw,2.3rem); font-weight:850; letter-spacing:-.03em; } .section-heading p { color:var(--muted); }
        .product-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:18px; } .product-card { background:#fff; border:1px solid var(--line); border-radius:16px; overflow:hidden; display:flex; flex-direction:column; } .product-card img { width:100%; aspect-ratio:1; object-fit:cover; background:#f0f3f1; } .product-body { padding:16px; display:flex; flex:1; flex-direction:column; } .product-name { color:var(--ink); text-decoration:none; font-size:1.06rem; line-height:1.4; font-weight:800; } .price { margin:11px 0; } .price strong { font-size:1.35rem; color:var(--brand); } .price del { color:#84918b; margin-left:7px; } .save { color:#a64709; background:#fff1e7; border-radius:6px; padding:4px 7px; font-size:.79rem; font-weight:800; }
        .card-actions { display:flex; gap:8px; margin-top:auto; } .card-actions .cta { flex:1; justify-content:center; padding:10px 8px; font-size:.9rem; }.card-actions .cta-outline { color:var(--brand); }
        .content-card { background:#fff; border:1px solid var(--line); padding:clamp(22px,4vw,42px); border-radius:18px; line-height:1.8; } .content-card img { max-width:100%; height:auto; border-radius:12px; } .story-image { width:100%; border-radius:18px; margin:22px 0; }
        .reviews { display:grid; grid-template-columns:repeat(4,1fr); gap:12px; } .reviews img { width:100%; aspect-ratio:1; object-fit:cover; border-radius:12px; background:#e8eeeb; }
        .sticky-cart { position:fixed; bottom:0; inset-inline:0; z-index:40; padding:10px 16px; background:rgba(255,255,255,.96); border-top:1px solid var(--line); backdrop-filter:blur(8px); } .sticky-cart-inner { max-width:760px; margin:auto; display:flex; justify-content:space-between; align-items:center; gap:12px; } #cart-message { color:var(--brand); font-weight:700; font-size:.9rem; }
        @media(max-width:767px) { .lp-shell { padding-inline:15px; } .hero { grid-template-columns:1fr; padding-top:22px; gap:20px; } .hero-media { order:-1; } .trust-row { grid-template-columns:1fr; margin-bottom:22px; } .product-grid { grid-template-columns:repeat(2,1fr); gap:10px; } .product-body { padding:12px; } .product-name { font-size:.92rem; } .price strong { font-size:1.1rem; } .price del { font-size:.8rem; display:block; margin-left:0; } .card-actions { flex-direction:column; } .reviews { grid-template-columns:repeat(2,1fr); } .lp-nav-inner .cart-link { font-size:.86rem; } }
    </style>
</head>
<body>
<nav class="lp-nav"><div class="lp-nav-inner">
    <a href="{{ route('home') }}" aria-label="Home">@if(optional($generalsetting)->white_logo)<img class="lp-logo" src="{{ asset($generalsetting->white_logo) }}" alt="{{ $generalsetting->name }}">@else {{ optional($generalsetting)->name }} @endif</a>
    <a class="cart-link" href="{{ route('customer.checkout') }}"><i class="fa fa-shopping-bag"></i> Cart <span id="cart-count">{{ Cart::instance('shopping')->count() }}</span></a>
</div></nav>
<main class="lp-shell">
    <section class="hero">
        <div class="hero-copy"><span class="eyebrow"><i class="fa fa-circle-check"></i> নির্বাচিত অফার</span><h1>{{ $campaign_data->banner_title ?: $campaign_data->name }}</h1>@if($campaign_data->daily_countdown || ($campaign_data->ends_at && $campaign_data->ends_at->isFuture()))<div class="offer-countdown" data-ends-at="{{ optional($campaign_data->ends_at)->toIso8601String() }}" data-daily-end="{{ $campaign_data->daily_countdown ? ($campaign_data->daily_countdown_end ?: '23:59') : '' }}"><span><b data-days>00</b><small>দিন</small></span><span><b data-hours>00</b><small>ঘণ্টা</small></span><span><b data-minutes>00</b><small>মিনিট</small></span><span><b data-seconds>00</b><small>সেকেন্ড</small></span></div>@endif<p>{!! strip_tags($campaign_data->short_description) !!}</p><a href="#products" class="cta">{{ $campaign_data->cta_text ?: 'অফারগুলো দেখুন' }} <i class="fa fa-arrow-down"></i></a></div>
        @if($campaign_data->banner)<div class="hero-media"><img src="{{ asset($campaign_data->banner) }}" alt="{{ $campaign_data->name }}" fetchpriority="high"></div>@endif
    </section>
    <section class="trust-row" aria-label="কেন আমাদের থেকে কিনবেন">
        <div class="trust"><i class="fa fa-truck-fast"></i><div><strong>দ্রুত ডেলিভারি</strong><small>সারা বাংলাদেশে ডেলিভারি</small></div></div>
        <div class="trust"><i class="fa fa-money-bill-wave"></i><div><strong>ক্যাশ অন ডেলিভারি</strong><small>পণ্য পেয়ে মূল্য পরিশোধ করুন</small></div></div>
        <div class="trust"><i class="fa fa-shield-heart"></i><div><strong>নিরাপদ কেনাকাটা</strong><small>সহজ অর্ডার ও সহায়তা</small></div></div>
    </section>
    <section id="products" data-builder-section="products" class="section"><div class="section-heading"><h2>আপনার জন্য নির্বাচিত পণ্য</h2><p>পছন্দের এক বা একাধিক পণ্য কার্টে যোগ করে একসাথে অর্ডার করুন।</p></div>
        <div class="product-grid">@foreach($products as $product)
            @php($discount = $product->old_price && $product->old_price > $product->new_price ? $product->old_price - $product->new_price : 0)
            <article class="product-card"><a href="{{ route('product', $product->slug) }}"><img loading="lazy" src="{{ asset(optional($product->image)->image ?: 'public/uploads/default/product.png') }}" alt="{{ $product->name }}"></a><div class="product-body"><a class="product-name" href="{{ route('product', $product->slug) }}">{{ $product->name }}</a><div class="price"><strong>৳{{ number_format($product->new_price) }}</strong>@if($product->old_price)<del>৳{{ number_format($product->old_price) }}</del>@endif</div>@if($discount)<span class="save">সাশ্রয় ৳{{ number_format($discount) }}</span>@endif<div class="card-actions mt-3"><button class="cta cta-outline add-to-cart" data-product-id="{{ $product->id }}">কার্টে যোগ করুন</button><form action="{{ route('cart.store') }}" method="POST">@csrf<input type="hidden" name="id" value="{{ $product->id }}"><input type="hidden" name="qty" value="1"><button class="cta" type="submit">এখনই কিনুন</button></form></div></div></article>
        @endforeach</div>
    </section>
    @if($campaign_data->image_one || $campaign_data->description)<section data-builder-section="story" class="section"><div class="content-card">@if($campaign_data->image_one)<img class="story-image" loading="lazy" src="{{ asset($campaign_data->image_one) }}" alt="{{ $campaign_data->name }} তথ্য">@endif{!! $campaign_data->description !!}@if($campaign_data->image_two)<img class="story-image" loading="lazy" src="{{ asset($campaign_data->image_two) }}" alt="পণ্যের বিস্তারিত">@endif@if($campaign_data->image_three)<img class="story-image" loading="lazy" src="{{ asset($campaign_data->image_three) }}" alt="পণ্যের বিস্তারিত">@endif</div></section>@endif
    @if($campaign_data->images->isNotEmpty())<section data-builder-section="reviews" class="section"><div class="section-heading"><h2>কাস্টমারদের অভিজ্ঞতা</h2><p>আমাদের পণ্য ব্যবহার করেছেন এমন গ্রাহকদের মতামত।</p></div><div class="reviews">@foreach($campaign_data->images as $review)<img loading="lazy" src="{{ asset($review->image) }}" alt="Customer review">@endforeach</div></section>@endif
@if(!empty($campaign_data->faq_items))<section data-builder-section="faq" class="section"><div class="section-heading"><h2>সচরাচর জিজ্ঞাসা</h2><p>অর্ডার করার আগে প্রয়োজনীয় উত্তর জেনে নিন।</p></div><div class="content-card">@foreach($campaign_data->faq_items as $faq)<details class="py-2 border-bottom"><summary class="fw-bold" style="cursor:pointer">{{ $faq['question'] }}</summary><p class="mb-0 mt-2 text-muted">{{ $faq['answer'] }}</p></details>@endforeach</div></section>@endif
</main>
<div class="sticky-cart"><div class="sticky-cart-inner"><span id="cart-message">পছন্দের পণ্য কার্টে যোগ করুন</span><a href="{{ route('customer.checkout') }}" class="cta">অর্ডার করুন <span id="sticky-cart-count">{{ Cart::instance('shopping')->count() }}</span></a></div></div>
<script>
document.querySelectorAll('.add-to-cart').forEach(button => button.addEventListener('click', async () => { const original = button.textContent; button.disabled = true; button.textContent = 'যোগ হচ্ছে…'; try { const response = await fetch('{{ route('campaign.cart.store') }}', {method:'POST', headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content}, body:JSON.stringify({id: button.dataset.productId, qty: 1})}); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'পণ্যটি যোগ করা যায়নি।'); document.querySelector('#cart-count').textContent = data.count; document.querySelector('#sticky-cart-count').textContent = data.count; document.querySelector('#cart-message').textContent = 'পণ্যটি কার্টে যোগ হয়েছে ✓'; button.textContent = 'যোগ হয়েছে ✓'; } catch (error) { document.querySelector('#cart-message').textContent = error.message; button.textContent = original; } finally { button.disabled = false; } }));
</script>
<script>document.querySelectorAll('.offer-countdown').forEach(function(timer){function target(){if(timer.dataset.dailyEnd){const [h,m]=timer.dataset.dailyEnd.split(':').map(Number),d=new Date();d.setHours(h,m,0,0);if(d<=new Date())d.setDate(d.getDate()+1);return d.getTime()}return new Date(timer.dataset.endsAt).getTime()}function tick(){const remaining=Math.max(0,target()-Date.now()),values={days:Math.floor(remaining/86400000),hours:Math.floor(remaining/3600000)%24,minutes:Math.floor(remaining/60000)%60,seconds:Math.floor(remaining/1000)%60};Object.keys(values).forEach(function(key){timer.querySelector('[data-'+key+']').textContent=String(values[key]).padStart(2,'0')})}tick();setInterval(tick,1000)});</script>
<script>const order=@json($campaign_data->section_order ?: ['products','story','reviews','faq']);const main=document.querySelector('.lp-shell');order.slice().reverse().forEach(key=>{const section=document.querySelector('[data-builder-section="'+key+'"]');if(section)main.insertBefore(section,main.querySelector('[data-builder-section]'))});</script></body></html>
