@extends('backEnd.layouts.master')
@section('title', 'Order Operations Board')
@section('css')
<style>.ops-board{display:flex;gap:14px;overflow-x:auto;padding-bottom:12px}.ops-column{min-width:285px;width:285px;background:#f3f6f4;border:1px solid #e0e8e3;border-radius:12px;padding:10px}.ops-column-head{display:flex;justify-content:space-between;align-items:center;padding:5px 4px 12px;font-weight:800}.ops-card{background:#fff;border:1px solid #e1e9e4;border-radius:10px;padding:12px;margin-bottom:10px;box-shadow:0 2px 8px rgba(20,45,33,.04)}.ops-card small{color:#738078}.ops-card textarea{font-size:.8rem}.ops-card .form-select{font-size:.78rem;padding:.35rem}.ops-empty{font-size:.85rem;color:#85908b;text-align:center;padding:28px 5px}</style>
@endsection
@section('content')
<div class="container-fluid"><div class="page-title-box d-flex justify-content-between align-items-center"><div><h4 class="page-title mb-1">Order operations board</h4><p class="text-muted mb-0">Status, staff assignment এবং internal note এক জায়গা থেকে manage করুন।</p></div><a class="btn btn-outline-primary" href="{{ route('admin.orders', ['slug'=>'all']) }}">Table view</a></div>
<div class="ops-board">@foreach($statuses as $status) @php($columnOrders = $orders->get($status->id, collect()))<section class="ops-column"><div class="ops-column-head"><span>{{ $status->name }}</span><span class="badge bg-primary rounded-pill">{{ $columnOrders->count() }}</span></div>@forelse($columnOrders as $order)<article class="ops-card"><div class="d-flex justify-content-between"><strong>#{{ $order->invoice_id }}</strong><span>৳{{ number_format($order->amount) }}</span></div><div class="mt-1">{{ optional($order->shipping)->name ?: optional($order->customer)->name }}</div><small>{{ optional($order->shipping)->phone }} · {{ $order->created_at->diffForHumans() }}</small><form class="mt-2" method="POST" action="{{ route('admin.orders.workflow', $order) }}">@csrf<select name="order_status" class="form-select mb-2">@foreach($statuses as $option)<option value="{{ $option->id }}" @selected($option->id == $order->order_status)>{{ $option->name }}</option>@endforeach</select><select name="user_id" class="form-select mb-2"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected($user->id == $order->user_id)>{{ $user->name }}</option>@endforeach</select><textarea name="admin_note" rows="2" class="form-control mb-2" placeholder="Internal note">{{ $order->admin_note }}</textarea><div class="d-flex justify-content-between align-items-center"><a href="{{ route('admin.order.process', ['invoice_id'=>$order->invoice_id]) }}" class="small">Details</a><button class="btn btn-sm btn-success">Save</button></div></form></article>@empty<div class="ops-empty">এই status-এ কোনো order নেই।</div>@endforelse</section>@endforeach</div></div>
@endsection
