@extends('backEnd.layouts.master')
@section('title','Online POS')
@section('css')
<link href="{{asset('public/backEnd')}}/assets/libs/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
<style>
.pos-shell{background:#f4f6f8;margin:-24px;padding:12px;min-height:calc(100vh - 70px)}.pos-panel{background:#fff;border:1px solid #dfe5e8;border-radius:8px;box-shadow:0 2px 5px #182f3c0c}.pos-head{padding:12px 16px;border-bottom:1px solid #e3e8eb;font-weight:800;font-size:18px}.pos-cart-table th{font-size:12px;color:#46535b;background:#f1f3f5}.pos-cart-table td{vertical-align:middle;font-size:13px}.pos-summary{border-top:2px solid #1b303b;padding-top:10px}.pos-form label{font-size:12px;font-weight:700;margin-bottom:3px}.pos-form .form-control,.pos-form .form-select{min-height:34px;font-size:13px}.product-grid-pos{display:grid;grid-template-columns:repeat(auto-fill,minmax(170px,1fr));gap:12px;padding:14px}.pos-product{position:relative;border:1px solid #e0e5e8;border-radius:6px;padding:8px;background:#fff;cursor:pointer;transition:.15s}.pos-product:hover{border-color:#087f5b;box-shadow:0 5px 14px #087f5b1c;transform:translateY(-1px)}.pos-product img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:4px}.pos-product h6{font-size:12px;font-weight:800;min-height:34px;margin:8px 0 3px}.variant-choice{border:1px solid #ddd;background:#fff;padding:8px 12px;font-size:13px}.variant-choice.active{background:#111;color:#fff;border-color:#111}.stock-pill{position:absolute;right:7px;top:7px;background:#0dbb64;color:#fff;border-radius:4px;padding:3px 6px;font-size:11px;font-weight:800}.variant-pill{display:inline-block;padding:2px 4px;background:#eef1f3;border-radius:3px;font-size:10px;margin:2px}.pos-total{font-size:19px;font-weight:900}.qty-controls button{border:0;border-radius:4px;width:24px;height:24px;font-weight:800}.qty-controls input{width:38px;border:1px solid #ced6da;text-align:center;height:24px}.pos-left{position:sticky;top:10px}.search-wrap{padding:14px;border-bottom:1px solid #e5e9eb}@media(max-width:991px){.pos-shell{margin:-12px}.pos-left{position:static;margin-bottom:14px}.product-grid-pos{grid-template-columns:repeat(2,1fr)}}
</style>
@endsection
@section('content')
<div class="pos-shell"><div class="row g-3"><div class="col-lg-5"><div class="pos-panel pos-left"><div class="pos-head d-flex justify-content-between align-items-center"><span><i class="fe-shopping-cart me-1"></i> Online POS</span><form action="{{route('admin.order.cart_clear')}}" method="GET"><button class="btn btn-sm btn-danger" onclick="return confirm('Clear POS cart?')">Clear <i class="fe-refresh-cw"></i></button></form></div><form action="{{route('admin.order.store')}}" method="POST" class="pos-form p-3" id="pos-order-form">@csrf
<table class="table table-sm pos-cart-table"><thead><tr><th>Name</th><th>Qty</th><th>Unit</th><th>Total</th><th></th></tr></thead><tbody id="cartTable">@include('backEnd.order.cart_content', ['cartinfo'=>$cartinfo])</tbody></table>
<div id="cart_details">@include('backEnd.order.cart_details')</div>
<div class="row g-2 mt-2"><div class="col-6"><label>Phone *</label><input id="phone" name="phone" class="form-control" required></div><div class="col-6"><label>Full Name *</label><input id="name" name="name" class="form-control" required></div><div class="col-12"><label>Address *</label><input id="address" name="address" class="form-control" required></div><div class="col-6"><label>Payment Method</label><select name="payment_method" class="form-select"><option>Cash</option><option>bKash</option><option>Nagad</option><option>Card</option><option>Cash On Delivery</option></select></div><div class="col-6"><label>Pay</label><input id="paid_amount" name="paid_amount" type="number" min="0" value="0" class="form-control"></div><div class="col-12"><label>Due</label><div class="pos-total" id="due_amount">৳0</div></div><div class="col-6"><label>Delivery Charge</label><select id="area" name="area" class="form-select" required><option value="">Select delivery</option>@foreach($shippingcharge as $charge)<option value="{{ $charge->id }}">{{ $charge->name }} — ৳{{ $charge->amount }}</option>@endforeach</select></div><div class="col-6"><label>Order Page</label><select name="order_page" class="form-select"><option value="">Select Page</option><option>Website</option><option>Facebook Page</option><option>WhatsApp</option><option>Phone Call</option><option>Physical Store</option></select></div><div class="col-12"><label>UTM Source</label><select name="utm_source" class="form-select"><option value="">Select UTM Source</option><option>Facebook Ads</option><option>Google Ads</option><option>TikTok</option><option>Organic</option><option>Influencer</option><option>Manual</option></select></div><div class="col-12"><label>Office Note</label><input name="office_note" class="form-control" placeholder="Only admin can see this"></div><div class="col-12"><label>Customer Note</label><input name="note" class="form-control" placeholder="Delivery/customer instruction"></div></div><button class="btn btn-success w-100 mt-3 fw-bold" id="place-order"><i class="fe-check me-1"></i> Place Order</button></form></div></div>
<div class="col-lg-7"><div class="pos-panel"><div class="pos-head"><i class="fe-package me-1"></i> Products <small class="text-muted fw-normal">Search to find products</small></div><div class="search-wrap"><input id="pos-search" class="form-control" autocomplete="off" placeholder="Search product by name or code…"></div><div class="p-3 text-center text-muted small" id="pos-empty-state">Search by product name or SKU to show products</div><div class="product-grid-pos d-none" id="pos-products">@foreach($products as $product)<article class="pos-product" data-name="{{ strtolower($product->name.' '.$product->product_code) }}" data-id="{{ $product->id }}"><span class="stock-pill">{{ $product->stock }}</span><img src="{{ asset(optional($product->image)->image ?: 'public/uploads/default/product.png') }}" alt="{{ $product->name }}"><h6>{{ $product->name }}</h6><strong>৳{{ number_format($product->new_price) }}</strong>@foreach($product->sizes as $size)<span class="variant-pill">{{ $size->sizeName }}</span>@endforeach</article>@endforeach</div></div></div></div></div>
<div class="modal fade" id="variantModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="variant-title">Select product options</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div id="variant-size-wrap" class="mb-3"><label class="fw-bold small">Select Size</label><div id="variant-sizes" class="d-flex gap-2 flex-wrap"></div></div><div id="variant-color-wrap" class="mb-3"><label class="fw-bold small">Select Color</label><div id="variant-colors" class="d-flex gap-2 flex-wrap"></div></div><input type="hidden" id="variant-product-id"></div><div class="modal-footer"><button class="btn btn-dark w-100" id="variant-add">Add to POS Cart</button></div></div></div></div>
@endsection
@section('script')
@php
$posProductOptions = $products->map(function ($product) {
    return ['id'=>$product->id,'name'=>$product->name,'sizes'=>$product->sizes->pluck('sizeName')->values(),'colors'=>$product->colors->pluck('colorName')->values()];
})->keyBy('id');
@endphp
<script>
const csrf='{{ csrf_token() }}';
function refreshPos(){ $.get('{{route('admin.order.cart_content')}}',d=>{$('#cartTable').html(d); refreshTotals();}); }
function refreshTotals(){ $.get('{{route('admin.order.cart_details')}}',d=>{$('#cart_details').html(d); updateDue();}); }
function updateDue(){ const total=parseFloat($('#pos-grand-total').data('amount')||0); const paid=Math.min(total,parseFloat($('#paid_amount').val())||0); $('#due_amount').text('৳'+Math.max(0,total-paid).toLocaleString()); }
const posOptions=@json($posProductOptions);const variantModal=new bootstrap.Modal(document.getElementById('variantModal'));let activePosProduct=null;function addPosProduct(id,size=null,color=null){$.get('{{route('admin.order.cart_add')}}',{id:id,product_size:size,product_color:color}).done(function(){refreshPos();variantModal.hide()}).fail(xhr=>toastr.error(xhr.responseJSON?.message||'Product cannot be added'))}$(document).on('click','.pos-product',function(){const product=posOptions[$(this).data('id')];activePosProduct=product;if(!product.sizes.length&&!product.colors.length){addPosProduct(product.id);return}$('#variant-title').text(product.name);$('#variant-product-id').val(product.id);$('#variant-sizes').html(product.sizes.map(size=>`<button type="button" class="variant-choice size-choice" data-value="${size}">${size}</button>`).join(''));$('#variant-colors').html(product.colors.map(color=>`<button type="button" class="variant-choice color-choice" data-value="${color}">${color}</button>`).join(''));$('#variant-size-wrap').toggle(product.sizes.length>0);$('#variant-color-wrap').toggle(product.colors.length>0);variantModal.show()});$(document).on('click','.variant-choice',function(){$(this).siblings().removeClass('active');$(this).addClass('active')});$('#variant-add').on('click',function(){const size=$('.size-choice.active').data('value')||null;const color=$('.color-choice.active').data('value')||null;if(activePosProduct.sizes.length&&!size){toastr.error('Please select a size');return}if(activePosProduct.colors.length&&!color){toastr.error('Please select a color');return}addPosProduct(activePosProduct.id,size,color)});
$(document).on('click','.cart_increment',function(){ $.get('{{route('admin.order.cart_increment')}}',{id:$(this).data('id')}).done(refreshPos).fail(xhr=>toastr.error(xhr.responseJSON?.message||'Stock unavailable')); });
$(document).on('click','.cart_decrement',function(){ $.get('{{route('admin.order.cart_decrement')}}',{id:$(this).data('id')}).done(refreshPos); });
$(document).on('click','.cart_remove',function(){ $.get('{{route('admin.order.cart_remove')}}',{id:$(this).data('id')}).done(refreshPos); });
$(document).on('change','.product_discount',function(){ $.get('{{route('admin.order.product_discount')}}',{id:$(this).data('id'),discount:$(this).val()}).done(refreshPos); });
$(document).on('change','#pos_discount',function(){ $.get('{{route('admin.order.cart_discount')}}',{discount:$(this).val()}).done(refreshPos); });
$('#area').on('change',function(){ $.get('{{route('admin.order.cart_shipping')}}',{id:$(this).val()}).done(refreshPos); });
$('#paid_amount').on('input',updateDue);
$('#pos-search').on('input',function(){const term=$(this).val().toLowerCase().trim();$('#pos-products').toggleClass('d-none',term.length<1);$('#pos-empty-state').toggle(term.length<1).text(term.length<1?'Search by product name or SKU to show products':'');$('.pos-product').each(function(){$(this).toggle($(this).data('name').includes(term));});if(term.length&&$('.pos-product:visible').length===0)$('#pos-empty-state').show().text('No product found');}).on('keydown',function(e){if(e.key==='Enter'){e.preventDefault();const first=$('.pos-product:visible').first();if(first.length)first.trigger('click')}});
$('#phone').on('blur',function(){const phone=$(this).val(); if(phone.length>=10) $.get('{{route('admin.pos.customer')}}',{phone}).done(c=>{if(c){$('#name').val(c.name||'');$('#address').val(c.address||'');}});});
$('#pos-order-form').on('submit',function(){const btn=$('#place-order'); if(this.checkValidity()){btn.prop('disabled',true).text('Saving order…');}});updateDue();
</script>
@endsection
