@extends('backEnd.layouts.master')
@section('title', 'Abandoned Carts')
@section('content')
<div class="container-fluid"><div class="page-title-box"><h4 class="page-title mb-1">Abandoned cart recovery</h4><p class="text-muted mb-0">Checkout শুরু করে order না করা customer-দের cart follow-up করার তালিকা।</p></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@error('reminder')<div class="alert alert-danger">{{ $message }}</div>@enderror
<div class="row g-3 mb-3"><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Active recovery opportunities</small><h3 class="mb-0">{{ number_format($summary['active']) }}</h3></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Potential cart value</small><h3 class="mb-0 text-success">৳{{ number_format($summary['recoverable_value']) }}</h3></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Recovered carts</small><h3 class="mb-0 text-primary">{{ number_format($summary['recovered']) }}</h3></div></div></div></div>
<div class="card"><div class="card-body"><div class="btn-group mb-3">@foreach(['active'=>'Active','recovered'=>'Recovered','ignored'=>'Ignored'] as $key=>$label)<a href="{{ route('abandoned-carts.index', ['status'=>$key]) }}" class="btn btn-sm {{ $status === $key ? 'btn-primary' : 'btn-outline-primary' }}">{{ $label }}</a>@endforeach</div><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Items</th><th>Customer</th><th>Cart value</th><th>Last activity</th><th>Status</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($carts as $cart)<tr><td><div class="fw-semibold">{{ count($cart->cart_data) }} item(s)</div><small class="text-muted">{{ collect($cart->cart_data)->pluck('name')->take(2)->implode(', ') }}{{ count($cart->cart_data) > 2 ? '…' : '' }}</small></td><td>{{ optional($cart->customer)->name ?: 'Guest checkout' }}<br><small class="text-muted">{{ $cart->phone ?: optional($cart->customer)->phone ?: 'Phone not captured yet' }}</small></td><td class="fw-semibold">৳{{ number_format($cart->subtotal) }}</td><td>{{ $cart->last_activity_at->diffForHumans() }}<br><small class="text-muted">{{ $cart->last_activity_at->format('d M, h:i A') }}</small></td><td><span class="badge {{ $cart->status === 'active' ? 'bg-soft-warning text-warning' : ($cart->status === 'recovered' ? 'bg-soft-success text-success' : 'bg-soft-secondary text-secondary') }}">{{ ucfirst($cart->status) }}</span></td><td class="text-end">@if($cart->status === 'active')@if($cart->phone)<form action="{{ route('abandoned-carts.reminder', $cart) }}" method="POST" class="d-inline">@csrf<button class="btn btn-sm btn-outline-success" @if($cart->last_reminder_at && $cart->last_reminder_at->gt(now()->subHours(6))) disabled title="Try again after 6 hours" @endif>SMS{{ $cart->reminder_count ? ' ('.$cart->reminder_count.')' : '' }}</button></form>@endif<form action="{{ route('abandoned-carts.ignore', $cart) }}" method="POST" class="d-inline">@csrf<button class="btn btn-sm btn-outline-secondary" onclick="return confirm('Ignore this cart?')">Ignore</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-5">এই status-এ কোনো cart পাওয়া যায়নি।</td></tr>@endforelse</tbody></table></div><div>{{ $carts->links() }}</div></div></div></div>
@endsection
