@extends('frontEnd.layouts.master')
@section('title','Shopping Cart')
@section('breadcrumb')Shopping Cart@endsection
@push('css')
<style>.cart-page{padding:28px 0 50px}.cart-layout{display:grid;grid-template-columns:1fr 330px;gap:24px;align-items:start}.cart-box,.summary-box{background:#fff;border:1px solid var(--line);border-radius:var(--radius);padding:22px}.cart-box h1,.summary-box h3{font-size:20px;font-weight:850;margin:0 0 18px;color:var(--ink)}.cart-row{display:grid;grid-template-columns:75px 1fr 100px 120px 110px 32px;gap:12px;align-items:center;border-top:1px solid var(--line);padding:13px 0;font-size:13px}.cart-row img{width:68px;height:68px;object-fit:cover;border-radius:10px}.cart-title{font-weight:800}.cart-qty{display:flex;border:1px solid var(--line);border-radius:9px;overflow:hidden;width:max-content}.cart-qty button{border:0;background:#f8fafc;width:30px;height:30px;cursor:pointer}.cart-qty button:hover{background:var(--green-soft);color:var(--green-dark)}.cart-qty input{border:0;outline:0;width:38px;text-align:center;font-weight:800}.cart-total{font-weight:800;color:var(--green-dark)}.remove-btn{border:0;background:none;color:#dc2626;font-size:15px;cursor:pointer}.summary-box{position:sticky;top:86px}.summary-box table{width:100%;font-size:13px}.summary-box td{padding:10px 0;border-bottom:1px solid var(--line)}.summary-box td.total{font-size:15px}.checkout-btn{display:block;background:var(--green);color:#fff;text-align:center;padding:14px;font-weight:850;border-radius:12px;margin-top:16px;transition:.18s;border:0}.checkout-btn:hover{background:var(--green-dark);transform:translateY(-1px)}.continue-link{display:block;text-align:center;margin-top:12px;font-size:13px;color:var(--green-dark);font-weight:700}.empty-cart{text-align:center;padding:40px 10px}.empty-cart i{font-size:40px;color:var(--green);margin-bottom:12px}@media(max-width:991px){.cart-layout{grid-template-columns:1fr}.summary-box{position:static}}@media(max-width:767px){.cart-layout{grid-template-columns:1fr;gap:14px}.cart-box,.summary-box{padding:15px}.cart-row{grid-template-columns:58px 1fr 28px;gap:9px}.cart-row img{width:54px;height:54px}.cart-row .cart-price,.cart-row .cart-total,.cart-row .cart-qty{grid-column:2}.cart-row .cart-qty{grid-row:3}.cart-row .cart-total{grid-row:4}.cart-row .cart-price{grid-row:2}}</style>@endpush
@section('content')
@php($subtotal=(int)str_replace([',','.00'],'',Cart::instance('shopping')->subtotal()))@php($shipping=(int)Session::get('shipping',0))@php($discount=(int)Session::get('discount',0))
<div class="fashion-container cart-page"><div class="cart-layout"><section class="cart-box"><h1>Shopping Cart <small class="text-muted fs-6">({{ Cart::instance('shopping')->count() }} items)</small></h1><div id="cartlist">@forelse($data as $item)<div class="cart-row"><img src="{{ asset($item->options->image) }}" alt="{{ $item->name }}"><div><div class="cart-title">{{ $item->name }}</div>@if($item->options->product_size)<small class="text-muted">Size: {{ $item->options->product_size }}</small>@endif @if($item->options->product_color)<small class="text-muted"> · Color: {{ $item->options->product_color }}</small>@endif</div><div class="cart-price text-muted">৳{{ number_format($item->price) }}</div><div class="cart-qty"><button class="cart_decrement" data-id="{{ $item->rowId }}">−</button><input value="{{ $item->qty }}" readonly><button class="cart_increment" data-id="{{ $item->rowId }}">+</button></div><div class="cart-total">৳{{ number_format($item->price*$item->qty) }}</div><button class="remove-btn cart_remove" data-id="{{ $item->rowId }}"><i class="fa fa-trash-can"></i></button></div>@empty<div class="empty-cart"><i class="fa fa-cart-shopping"></i><h5 class="fw-bold">আপনার কার্ট খালি</h5><p class="text-muted">পছন্দের পণ্য কার্টে যোগ করে অর্ডার করুন।</p><a class="checkout-btn d-inline-block" style="width:auto;padding:12px 24px" href="{{ route('home') }}">শপিং শুরু করুন</a></div>@endforelse</div></section><aside class="summary-box"><h3>Order Summary</h3><table><tr><td>Subtotal</td><td class="text-end">৳{{ number_format($subtotal) }}</td></tr><tr><td>Shipping</td><td class="text-end">৳{{ number_format($shipping) }}</td></tr><tr><td>Discount</td><td class="text-end" style="color:var(--green-dark)">- ৳{{ number_format($discount) }}</td></tr><tr><td class="total"><strong>Total</strong></td><td class="text-end total"><strong>৳{{ number_format($subtotal+$shipping-$discount) }}</strong></td></tr></table><a class="checkout-btn" href="{{ route('customer.checkout') }}"><i class="fa fa-lock me-2"></i>Proceed to Checkout</a><a class="continue-link" href="{{ route('home') }}">← Continue Shopping</a></aside></div></div>
@endsection
