@extends('frontEnd.layouts.master')
@section('title', 'Return Requests')
@section('content')
<section class="customer-section"><div class="container"><div class="row"><div class="col-sm-3"><div class="customer-sidebar">@include('frontEnd.layouts.customer.sidebar')</div></div><div class="col-sm-9"><div class="customer-content"><h5 class="account-title">Return / Refund Request</h5>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card mb-4"><div class="card-body"><p class="text-muted">পণ্য ফেরত বা refund দরকার হলে order নির্বাচন করে কারণ লিখুন। Request approve হলে আমাদের team পরবর্তী নির্দেশনা দেবে।</p><form method="POST" action="{{ route('customer.returns.store') }}">@csrf<div class="mb-3"><label class="form-label">Order নির্বাচন করুন</label><select name="order_id" class="form-select @error('order_id') is-invalid @enderror" required><option value="">একটি order নির্বাচন করুন</option>@foreach($orders as $order)<option value="{{ $order->id }}" @selected(old('order_id') == $order->id)>#{{ $order->invoice_id }} — ৳{{ number_format($order->amount) }} ({{ $order->created_at->format('d M Y') }})</option>@endforeach</select>@error('order_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="mb-3"><label class="form-label">ফেরত/রিফান্ডের কারণ</label><textarea name="reason" class="form-control @error('reason') is-invalid @enderror" rows="4" required minlength="10" placeholder="পণ্যের সমস্যা বা return-এর কারণ লিখুন">{{ old('reason') }}</textarea>@error('reason')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><button class="btn btn-success">Request submit করুন</button></form></div></div>
<div class="card"><div class="card-body"><h6 class="mb-3">আপনার return request</h6><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Order</th><th>Reason</th><th>Status</th><th>Update</th></tr></thead><tbody>@forelse($returnRequests as $return)<tr><td>#{{ optional($return->order)->invoice_id }}</td><td>{{ Str::limit($return->reason, 70) }}</td><td><span class="badge {{ $return->status === 'approved' ? 'bg-success' : ($return->status === 'rejected' ? 'bg-danger' : 'bg-warning text-dark') }}">{{ ucfirst($return->status) }}</span></td><td>{{ $return->admin_note ?: ' অপেক্ষমান' }}<br><small class="text-muted">{{ $return->created_at->format('d M Y') }}</small></td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-4">এখনও কোনো return request নেই।</td></tr>@endforelse</tbody></table></div></div></div>
</div></div></div></div></section>
@endsection
